optimizer:
  name: adam
  lr: 1.0e-3

train:
  epoch: 200
  batch_size: 32
  seed: 2024
  input_dim: 128
  hidden_dim: 200
  max_seq_length: 100
  dropout: 0.2
  kq_same: 1
  n_blocks: 4
  maxgradnorm: -1
  GPU: cuda
  q_gamma: 0.03
  d_ff: 1024
  n_heads: 8
  final_fc_dim: 512
  memory_size: 60
  window_size: 30


test:
  metrics: [auc, acc]
